name: Refresh

on:
  schedule:
    - cron: '0 */2 * * *'
    
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: node -e "fetch('https://github.com/ShirasawaSama').then(a=>a.text()).then(a=>[...a.matchAll(/src=\"https:\/\/camo.githubusercontent.com\/(.+?)\"/g)].forEach(b=>fetch('https://camo.githubusercontent.com/'+b[1]).then(c=>c.text())))"
